FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2

src/main/java/com/kdt_y_be_toy_project2/domain/model/TimeScheduleInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripType.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java

[feat] 여행 엔티티 개발

---

src/main/java/com/kdt_y_be_toy_project2/global/error/ApplicationException.java
src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorResponse.java
src/main/java/com/kdt_y_be_toy_project2/global/error/GlobalExceptionHandler.java

Feature/Global Exception Handler 추가

---

src/main/java/com/kdt_y_be_toy_project2/global/util/DateTimeUtil.java

[feat] 공통 유틸리티 클래스 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidDateException.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidItineraryDurationException.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/ItineraryNotFoundException.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java

[feat] 여정 Exception 개발

---

src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java

Motivation:
- 세미 콜론으로 인해 발생한 컴파일 에러를 수정합니다.
Modification:
- 세미콜론 제거

[fix] `ErrorCode` Compile Error 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
src/main/java/com/kdt_y_be_toy_project2/global/util/DateTimeUtil.java

[refactor] TripRequest에 공통 유틸리티 클래스 적용

---

src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/AccommodationInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/MoveInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/StayInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/AccommodationInfoRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/MoveInfoRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/StayInfoRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
src/main/java/com/kdt_y_be_toy_project2/domain/model/DateScheduleInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/model/DateTimeScheduleInfo.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
src/test/java/com/kdt_y_be_toy_project2/domain/model/DateTimeScheduleInfoTest.java

Motivation
- 여행 등록, 수정, 조회 시 발생할 수 있는 예외에 대한 검증
Modification
- 여행에는 시간이 필요없기 때문에 DateScheduleInfo.java 생성
- DateScheduleInfo 생성시 여행 시간 관련 검증 로직 추가
- 클래스 이름의 명확성을 위해 TimeScheduleInfo -> DateTimeScheduleInfo 변경

[feat] 여행 검증 및 예외처리

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/resources/application.yaml

[refactor] Trip Entity 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripType.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripTypeConverter.java

[feat] TripType.java에 한글 value 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
src/main/java/com/kdt_y_be_toy_project2/global/util/DateTimeUtil.java

Motivation
- @Pattern 정규식 문제 수정
Modification
- @Pattern 정규식 변경

[fix] 패턴 애노테이션 정규식 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java

[fix] 여행 도메인의 DTO의 TripType 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/DateScheduleInfoTestFactory.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java

[test] 여행 컨트롤러 통합 테스트 성공 케이스 작성 

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
src/main/java/com/kdt_y_be_toy_project2/global/config/OpenApi3Config.java

[docs] 여행 API Swagger 문서화

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java

Motivation:
- 여행 서비스의 유닛 테스트
Modification:
- 여행 서비스 클래스에 있는 메소드에 대한 테스트

[test] 여행 서비스 유닛 테스트 코드 작성

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java

[fix] 여행 조회 시 무한 순환 참조 문제

---

src/main/java/com/kdt_y_be_toy_project2/global/error/GlobalExceptionHandler.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java

[test, feat] 여행 도메인 통합 테스트(실패케이스) 작성 및 바인딩 핸들러 추가

---

src/main/resources/application-dev.yaml
src/main/resources/application-test.yaml
src/main/resources/application.yaml

[fix] applicaiton.yaml 수정 및 profiles 파일 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripTypeConverter.java

Motivation:
- #80 을 참고해주세요.
Modification:
- `TripTypeConverter.java`에 `@Converter` 주석 추가

[fix] 국내외여부 enum 변환 클래스에 `@Converter` 주석 추가

---

build.gradle
src/main/java/com/kdt_y_be_toy_project2/global/jwt/JwtPayload.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/JwtProvider.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/exception/BadTokenException.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/exception/TokenExpiredException.java
src/main/resources/application-test.yaml
src/main/resources/application.yaml
src/test/java/com/kdt_y_be_toy_project2/global/jwt/JwtProviderTest.java
src/test/resources/application.yaml

* #87 
* a673c99
* 0198568
Close #87

 JWT 발급 및 검증 기능 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryController.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/Itinerary.java
src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java

1. 여정 Entity에 NotNull 추가,  2. 서비스 중복 로직 모듈화

---

src/main/java/com/kdt_y_be_toy_project2/global/config/CustomHttpHeaders.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/JwtProvider.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationProvider.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationToken.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtPair.java

motivation:
- 로그인 성공 시 Jwt Token을 부여하고, 매 요청마다 Jwt Token을 확인하는 필터가 필요하게 되었습니다.
modification:
- Jwt를 검증하는 `JwtFilter`, `JwtProvider` 추가
- Custom Header 추가
Close #98

[feat] Jwt 인증 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripSearchRequest.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/exception/TripSearchIllegalArgumentException.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java

여행 검색 기능 추가

---

build.gradle
src/main/java/com/kdt_y_be_toy_project2/global/config/RedisConfig.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/JwtProvider.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/api/JwtRefreshController.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/api/RefreshTokenRequest.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/repository/JwtEntity.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/repository/JwtRedisRepository.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/repository/JwtRepository.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/repository/TokenType.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/service/JwtService.java
src/main/java/com/kdt_y_be_toy_project2/global/jwt/service/TokenPair.java
src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityConfig.java
src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityFilterConfig.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationProvider.java
src/test/java/com/kdt_y_be_toy_project2/global/helper/ControllerUnitTestHelper.java
src/test/java/com/kdt_y_be_toy_project2/global/jwt/JwtProviderTest.java
src/test/java/com/kdt_y_be_toy_project2/global/jwt/service/JwtServiceTest.java

`RefreshToken`을 저장하고 `accessToken`을 재발급하는 기능을 추가했습니다.
Close #115

refreshToken 기능추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryController.java

Motivation:
- 인증 관련 Swagger 추가

[docs] ItineraryController 인증 관련 Swagger 추가

---

build.gradle
src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomFormLoginFilter.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationProvider.java
src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationToken.java
src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/ItineraryTestFactory.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
src/test/java/com/kdt_y_be_toy_project2/integration/TripAndItineraryIntegrationTest.java

- `@WithMockUser` 어노테이션을 추가해서 권한으로 인한 오류를 임시로 회피했습니다.
closes #111

여행 컨트롤러 통합 테스트 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/StayInfo.java

[refactor] StayInfo 테이블 매핑 컬럼명 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/member/exception/MemberNotFoundException.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java

MemberNotFoundException 추가

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Likes.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripIntegrationTest.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepositoryTest.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
src/test/java/com/kdt_y_be_toy_project2/integration/TripAndItineraryIntegrationTest.java

댓글 기능을 제외한 레이어별 여행 유닛 테스트를 개발한다.

---

src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java

Motivation:
- #132 를 참고해주세요
Close #132

여정 controller 유닛 테스트 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/member/domain/Member.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Comment.java
src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java

Motivation:
- #135 를 참고하세요.
Modification:
- Comment, Trip, Member 엔티티 수정
close #135

댓글 관련 엔티티 수정

---

src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripIntegrationTest.java
src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java
src/test/java/com/kdt_y_be_toy_project2/global/factory/MemberTestFactory.java

유닛, 통합 테스트 오류 수정
